/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0b27cffc8ba4cdba61505027e8ccefa4)
interface __BaseEnv_Env {
  AI: Ai
  DiagramAgent: DurableObjectNamespace<import('./src/server').DiagramAgent>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server')
    durableNamespaces: 'DiagramAgent'
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
